### ISSUE TITLE
Error on single export

### ISSUE THREAD

**Issue by ExternalReality** [knupfer/haskell-emacs#13]
It appears that a situation can arise where `haskell-emacs-init` expects a module to export a list of symbols and errors out in the case when a compiled module only exports one.

`module Mod where`       -- OK  (in the case where nothing exported at all)
`module Mod where`          -- OK (in the case where multiple things are exported)
`module Mod (x, y) where` -- OK 
`module Mod (x) where`     -- Not OK 

emacs messages the following when encountering the error: `error in process filter: when expecting a list, encountered string instead`

**Comment by knupfer** [comment]
Ah, I'll have to dig into the elisp part... I'll fix it this week, thanks for reporting!

**Comment by knupfer** [comment]
fixed thanks to your commit
