### ISSUE TITLE
improve parsing of functions to export

### ISSUE THREAD

**Issue by knupfer** [knupfer/haskell-emacs#15]
At the moment, only functions from modules will be considered which are exported explicitly, and these functions are in an unelegant way (simply using functions like unwords and co on the sourcecode as a string).

A way forward would be using something like ghc or th to inspect the module.

**Comment by knupfer** [comment]
the same is true for documentation

**Comment by ExternalReality** [comment]
https://github.com/knupfer/haskell-emacs/pull/19

Will exports all functions when export list is omitted. Will only capture the exports relevant to haskell-emacs (funtions names).

I am not sure what to do about module exports -- it should probably recurse into the module and capture that modules function names.

**Comment by knupfer** [comment]
this is fixed, for the docs I open a new issue
