### ISSUE TITLE
Make emacs package setup easier

### ISSUE THREAD

**Issue by ExternalReality** [knupfer/haskell-emacs#20]
Should installing the package be easier? User have to do something akin to the following:

http://www.stackbuilders.com/news/having-fun-with-emacs-in-haskell

To use the package. Perhaps using `stack` in the install script (or something similar) can improve the ease of installation for most users.

**Comment by knupfer** [comment]
I think it would be good to let haskell-emacs autorecognize if haskell-fun contains a sandbox and use the libraries in it. So the user wouldn't need to configure anything, with or without sandbox. It could as well install automatically the dependencies of haskell-emacs into that sandbox, but perhaps that would be surprising: a elisp library which installs without asking haskell libraries...

**Comment by knupfer** [comment]
Let's implement an install dialog, which asks if the user wishes to use sandboxes and if it should try to cabal install the needed dependencies

**Comment by knupfer** [comment]
With commit 24cc4fb61bc082ed33b44b68bd437ebff95bed9e installation is dead simple.  If the user hasn't got a `haskell-emacs' directory, he'll get an installation dialog asking him whether he would like to have a cabal sandbox (into his haskell-emacs dir), whether he would like to install the missing dependencies and if the user likes to have an example added.

Cabal sandboxes in `haskell-emacs-dir' get autorecognized, so fuzzing with the ghc-flags is as well no longer necessary.
