### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by ExternalReality** [knupfer/haskell-emacs#24]
Which continuous integration platform should be used for this project. I would not mind setting up a [CircleCI](https://circleci.com/) build since I am familiar with that platform.

**Comment by knupfer** [comment]
Stuff on github uses usually travisCI. To my knowledge, travis supports more open source and they've open sourced (parts of) their product. So I would suggest travis. Besides that, I'm very interested in bake from ndmitchell.

**Comment by knupfer** [comment]
implemented with PR #41
