### ISSUE TITLE
Error when executing (haskell-emacs-init)

### ISSUE THREAD

**Issue by ahmadnazir** [knupfer/haskell-emacs#29]
Hi,

I am getting the following error when running (haskell-emacs-init) in emacs:

```
Debugger entered--Lisp error: (error "
.HaskellEmacs.hs:26:18:
    Could not find module `Language.Haskell.Exts.Syntax'
    Perhaps you meant
      Language.Haskell.TH.Syntax (from template-haskell)
    Use -v to see a list of the files searched for.
")
..
  eval-defun-2()
  eval-defun(nil)
  call-interactively(eval-defun nil nil)
  command-execute(eval-defun)
```

**ghc --version**
`
The Glorious Glasgow Haskell Compilation System, version 7.6.3
`

**cabal --version**
`
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
`

According to the documentation, if `ghc` and `cabal` are installed, the haskell dependencies will automatically be installed which is why I haven't manually installed the following:
- atto-lisp
- parallel
- utf8-string

Nevertheless, the error message seems to be unrelated.

Appreciate your help.

Thanks!

**Comment by knupfer** [comment]
Thanks, it should work now. If not, please reopen or report another issue. Please note, that you have to remove the haskell-fun directory (~/.emacs.d/haskell-fun) to receive another installation prompt.

**Comment by ahmadnazir** [comment]
Thanks for the quick reply. I see another problem which I'll report separately.
