### ISSUE TITLE
haskell-src-exts fails to install

### ISSUE THREAD

**Issue by ahmadnazir** [knupfer/haskell-emacs#33]
I can see that now the haskell-src-exts dependency fails to install when calling M-x haskell-emacs-init:

```
..
In-place registering atto-lisp-0.2.2...
Creating package registration file: /tmp/pkgConf-atto-lisp-0.230897.2
Installing library in
/path/to/emacs.d/haskell-fun/.cabal-sandbox/lib/x86_64-linux-ghc-7.6.3/atto-lisp-0.2.2
Registering atto-lisp-0.2.2...
Installed atto-lisp-0.2.2
cabal: Error: some packages failed to install:
haskell-src-exts-1.16.0.1 failed during the configure step. The exception was:
ExitFailure 1
```

Any ideas what might be the reason?

**Comment by knupfer** [comment]
Could you try to `cabal install happy` manually before the installation process and then run `haskell-emacs-init` without sandbox (beforehand you should rm your haskell-fun directory)? If you don't like installing without sandbox, just add "happy" in `haskell-emacs.el` between "install" and "atto-lisp".

Does this work?

**Comment by ahmadnazir** [comment]
That worked .. thanks. I created a pull request for it.
