### ISSUE TITLE
Use GHC 7.10

### ISSUE THREAD

**Issue by ExternalReality** [knupfer/haskell-emacs#39]
I would enjoy support for GHC 7.10. Doing this would be simple. It would require:
- [ ] Fork atto-lisp
- [ ] [Relax upper-bound on deepseq](https://github.com/nominolo/atto-lisp/issues/18)
- [ ] [Relax  upper-bound on blazebuilder](https://github.com/nominolo/atto-lisp/issues/16)
- [ ] Depend on the forked repo.

**Comment by knupfer** [comment]
Oh, I wasn't aware of that. I'm actually on GHC 7.10.2 without problems, but perhaps the version in nix is patched. I'll look into that.

**Comment by knupfer** [comment]
Perhaps it would be better to incorporate atto-lisp into this repo. This would avoid complicating installations via melpa.

**Comment by ExternalReality** [comment]
@knupfer Using a Git sub-module?

**Comment by knupfer** [comment]
@ExternalReality I've looked into that, but the simplest solution seems to be, to use something like
`cabal install --allow-newer=bar --constraint="bar==2.1"` in the installation procedure. This would avoid
- cluttering the repo
- have a sandbox depending on a sandbox

and could be automated in an easy way.
What do you think?

**Comment by knupfer** [comment]
this works now even for ghcHEAD
