### ISSUE TITLE
spacemacs with old ghc doesn't work

### ISSUE THREAD

**Issue by ngksternhagen** [knupfer/haskell-emacs#50]
EDIT -- Heavy and protracted CPU use during haskell-emacs init is _not_ expected, so my original request for documentation isn't really valid. Also edited for accuracy and brevity.

I tried to install haskell-emacs using additional-packages in spacemacs, but I was using an old GHC. This failed in a dramatic way.

After installing the haskell-emacs package (I use Spacemacs, so this was handled by the dotspacemacs-additional-packages function) I did M-x haskell-emacs-init and answered yes to the prompts. 

My emacs then was blocked, and CPU load on my laptop went to near 100% (on 1 of 4 cores) for several hours before I killed the emacs process.

Thanks for writing this tool, I'm very excited to hack around with haskell-emacs once it's up and running.

**Comment by knupfer** [comment]
hi ngksternhagen,

this is quite strange.  The first initialization should take something
like 5 minutes to download some dependencies and print at the same time
feedback to the message prompt what it's doing at the moment.  The
interesting part of your problem is that your CPU is busy so it hasn't
crashed.  Well, if your cpu is _very_ slow it is possible...

It has terminated by now?  If not, what were the messages printed to
your prompt (or in the message buffer)?  What is the contents of your
~/.emacs.d/haskell-fun ?  Is there a "Matrix.hs", a ".HaskellEmacs.hs",
a ".HaskellEmacs", a ".cabal"?

Greets

**Comment by ngksternhagen** [comment]
I suspended the machine for most of the day. After resume, the emacs process is still running as before. From what you've said it sounds like a bug in either haskell-emacs or spacemacs. I'll look into this later this evening and post a response to your questions above, plus some more information about my environment.

**Comment by ngksternhagen** [comment]
my environment is (please let me know if more details are needed):
- Spacemacs 0.103.2
- haskell-platform package installed through apt, version 
  2013.2.0.0.debian12
- GHC version 7.6.3
- cabal-install version 1. 20.0.3 using version 1.20.0.2 of the Cabal library

**Comment by knupfer** [comment]
Albeit your GHC is ancient and I strongly recommend that you switch to a newer one (via ppa:hvr/ghc), according to travis it should work...

Would you mind posting the other informations?  Were there any messages? How does your ~/.emacs.d/haskell-fun folder look? Is there a file ~/.emacs.d/haskell-fun/.HaskellEmacs.hs and if yes, does it contain the string "Matrix" somewhere? Have you got a standard emacs at hand and could check whether it works with this one?
Could you try to manually install the dependencies via cabal?

Greets and thanks for your debugging!

**Comment by knupfer** [comment]
I've installed spacemacs and it works on my side flawlessly, with the dotspacemacs-additional-packages variable and with the traditional (package-list-packages).
I've got 
- spacemacs 0.104.2
- GHC 7.10.2
- cabal 1.22.6.0

greets

**Comment by ngksternhagen** [comment]
So the moral of the story (as with many other Haskell stories it seems) is that ubuntu's haskell-platform package really is not your friend. I will also install the versions listed above and verify the fix.

To provide the other requested information (for posterity):
- I didn't see any message from emacs when I hit this unsupported version issue -- in fact, the GUI emacs window went blank.
- ~/.emacs.d/haskell-fun was created and it had the file .HaskellEmacs.hs, haskell-emacs.el and also files for the example functions. 
- I think I will skip (at least for now) trying to install with combination of old GHC and standard emacs, since it's recommended to use new GHC in any case.
