### ISSUE TITLE
Please provide support for stack

### ISSUE THREAD

**Issue by michaelp** [knupfer/haskell-emacs#53]
Please add support for stack as an alternative to cabal sandbox

**Comment by knupfer** [comment]
I'm working on it

**Comment by michaelp** [comment]
Please let me know if you need help in testing.

**Comment by michaelp** [comment]
Any updates?

**Comment by knupfer** [comment]
It's on my todo list.  I was busy with relocation...

**Comment by mwotton** [comment]
@knupfer really looking forward to the stack port :) looks like a lovely piece of work, wish i'd seen it before I wrote https://github.com/mwotton/emacsplugin

Do you need any help on the stack backend? You've already achieved 90% of what I wanted, so I'm happy to put in some time.

**Comment by knupfer** [comment]
So, sorry for the delay.  With the recent push, you can easily use stack, cabal or nix.
@mwotton Could you verify please that it works with stack as you like? I use normally nix, which interacts a bit with stack...

**Comment by mwotton** [comment]
thanks, seems to install, at least. I'm a bit confused by what I have to do to make the example Matrix library visible, though - I copied it to the right place (~/.emacs.d/haskell-fun/Matrix.hs),  but (Matrix.identity 1) in a scratch buffer just tells me the symbol's definition is void. I haven't customised haskell-emacs other than setting the build-tool to stack. Any ideas what I'm missing?

**Comment by knupfer** [comment]
Have you run
M-x haskell-emacs-init
? It copies the example and stuff.
Could you provide a ls of your haskell-fun directory?

**Comment by mwotton** [comment]
ah, ok - didn't realise i needed to run it every time i added a new file. That's the standard workflow?

**Comment by mwotton** [comment]
(the example is working now, thanks)

**Comment by knupfer** [comment]
Yes, you have to rerun haskell-emacs-init when adding a new file or changing a file. I'm not aware of an other sensible default. Recompiling on every edit? That would be very expensive...

**Comment by mwotton** [comment]
it makes sense in retrospect. might be worth making a note of it though? "haskell-emacs-init" sounds like something you run once, rather than rerunning constantly during development.

**Comment by knupfer** [comment]
Thanks for the pointer, I've updated the readme

**Comment by mwotton** [comment]
hm. one difficulty: it seems like haskell-emacs-init unconditionally overwrites the stack.yaml - this is a bit of a problem, as that's where you control extra packages and the like...

**Comment by knupfer** [comment]
Fixed! (please consider opening new issues)
Thanks

**Comment by mwotton** [comment]
heh, righto :)

**Comment by michaelp** [comment]
Great News! Thank you for your work.
