### ISSUE TITLE
haskell-emacs-init asks whether to save the HaskellEmacs.hs buffer

### ISSUE THREAD

**Issue by mwotton** [knupfer/haskell-emacs#55]
given that it's completely under haskell-emacs' control, might it makes sense to overwrite it unconditionally? If someone's silly enough to try to edit it manually, I feel like they deserve everything they have coming to them.

**Comment by knupfer** [comment]
I fear that I can't reproduce this issue. On my side it overwrites it unconditionally...
Have you already tried with `emacs -Q` ?

**Comment by mwotton** [comment]
ah, probably just my config then. sorry about the noise.
