### ISSUE TITLE
Allow choice of executable path

### ISSUE THREAD

**Issue by pthariensflame** [knupfer/haskell-emacs#59]
Right now, `haskell-emacs` is unusable for me because it can't find `stack` (or `cabal`, `nix`, or `ghc`, for that matter).  I've looked at the customization interface, but it doesn't allow me to specify that I want the use `~/.local/bin/stack`, rather than it trying (and failing) to pick up an executable named `stack` from a nonexistent `PATH`.

**Comment by mwotton** [comment]
Is it not acceptable to add $HOME/.local/bin  to the emacs PATH variable?

**Comment by pthariensflame** [comment]
@mwotton It's unfortunately not possible for me to modify my `PATH` at all; I'm using [Aquamacs](http://aquamacs.org), which means that it launches as an application and I don't get the chance to alter its environment.

**Comment by mwotton** [comment]
I don't mean the PATH in the environment, I mean the emacs PATH - you can
set it in your .emacs. see https://www.emacswiki.org/emacs/ExecPath

**Comment by pthariensflame** [comment]
Oh, I didn't even know that was a thing.  😆 Ok, having solved the problem, I'll close this issue.

**Comment by bitemyapp** [comment]
@pthariensflame not to get all up ons, but most Emacs+Mac OS X users don't use Aquamacs. Are you sure the underlying version of Emacs in your Aquamacs install has FFI?
