### ISSUE TITLE
Avoid recompilation if nothing has changed in /haskell-fun

### ISSUE THREAD

**Issue by jonschoning** [knupfer/haskell-emacs#63]
`haskell-emacs-init` seems to take a full 20 seconds each time it is invoked, even if nothing in `~/.emacs-d/haskell-fun` has changed.  Manually invoking `stack install` in `~/.emacs-d/haskell-fun` is nearly instantateous, but `haskell-emacs-init` takes ~20 seconds each time.  

Can this delay be shortened to the same time that manually invoking `stack install` would take?

This would allow one to have haskell-emacs start in the emacs startup init script (invoking `haskell-emacs-init`) very easily.

**Comment by knupfer** [comment]
Thanks for reporting!
I think I know the reason for that, at the moment it calls on init unconditionally `stack setup && stack install`, so it seems that `stack setup` is eating the time here.

I'll try it tomorrow with `stack`.
