### ISSUE TITLE
Please, revive the project

### ISSUE THREAD

**Issue by Anton-Latukha** [knupfer/haskell-emacs#71]
Project has good documentation & the state seems great, but it became a bit rusty in 5 years.

As we know - Haskell & Elisp code stands the test of time perfectly.

Haskell tooling arrived - it seems a nice time to clean the dust out of FFI.

I would help with it, as I am interested in learning FFIs, especially between Haskell and a such classic as Lisp (& as Emacs guy).

I would like much to discuss adding FFI with `lsp-haskell`. & to have&know Haskell-Emacs integration overall.

**Comment by francesquini** [comment]
After some tinkering I got it to run on newer GHCs (9.X+) (https://github.com/francesquini/haskell-emacs). 
I can create a pull request if there is interest.

**Comment by walseb** [comment]
> After some tinkering I got it to run on newer GHCs (9.X+) (https://github.com/francesquini/haskell-emacs). I can create a pull request if there is interest.

Thank you! I have been meaning to try to get it to compile again.

**Comment by francesquini** [comment]
> > After some tinkering I got it to run on newer GHCs (9.X+) (https://github.com/francesquini/haskell-emacs). I can create a pull request if there is interest.
> 
> Thank you! I have been meaning to try to get it to compile again.

PR created. https://github.com/knupfer/haskell-emacs/pull/72
